plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id("io.freefair.lombok") version "9.1.0"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }

    maven {
        name "REI"
        url "https://maven.shedaniel.me/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
            includeGroup "dev.architectury"
        }
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    api "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // FIXME REI not available for the snapshot yet
    //  edit: adding just api, have to disable transitive dependencies because api still brings in a lot of not available things
    //  edit 2: nope, still doesn't work because it's not remapped, get things like "Item in not assignable to class_123",
    //          excluding `mod_compat/roughlyenoughitems` package for now
//    api ("me.shedaniel:RoughlyEnoughItems-api-fabric:${project.rei_version}") {
//        transitive = false
//    }
//    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
//    modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${project.rei_version}"

    api("mezz.jei:jei-${project.minecraft_version}-fabric-api:+")
    implementation("mezz.jei:jei-${project.minecraft_version}-fabric:+")
}

sourceSets {
    main {
        java {
            exclude 'io/github/reoseah/hayo/mod_support/roughlyenoughitems/**'
        }
    }
}

loom {
    accessWidenerPath = file("src/main/resources/hayo.classtweaker")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {}
}