# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

org.gradle.java.home=/home/bohdan/.jdks/openjdk-25

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-2
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=io.github.reoseah.hayo
archives_base_name=hayo-industries

# Dependencies
fabric_api_version=0.141.2+26.1
rei_version=21.9.812
jei_version=28.3.0.11